### ISSUE TITLE
Timer Fix

### ISSUE THREAD

**Issue by saiij** [saiij/editable-web-quiz#3]
## Problem: 
The Timer bugs(Resume with next question or just fill the bar again) when you save and exit a game and then play with this savegame again.

## How should it be: 
The save function should create a "frozen game" like a pause Button so when you resume the game continuous exactly on this Question with the correct amount of time left.

**Comment by MSSR-code** [comment]
Can i resolve this bug?

**Comment by MSSR-code** [comment]
> Can i resolve this bug?

i just opened a pr fixing  this issue.

**Comment by saiij** [comment]
Thanks buddy!
