### ISSUE TITLE
Make the timer bar smoother

### ISSUE THREAD

**Issue by saiij** [saiij/editable-web-quiz#32]
# Problem:
The timer ticks down every second. That makes the timer bar very volatile.
It would be better if the timer bar ticks down smoother maybe every 10ms or so while the timer itself still counts in seconds.

## How to contribute:
Fix the issue and feel free to add your name to the readme file.

**Comment by BlueFRJ** [comment]
Hi! I'd love to work on this one :D

**Comment by saiij** [comment]
@BlueFRJ okay it's yours! Good luck.
