### ISSUE TITLE
[EASY] Add categories to the questions.

### ISSUE THREAD

**Issue by saiij** [saiij/editable-web-quiz#40]
# Problem:
We've collected a bunch of questions together.
Now we need to tag them with a category so they can get accessed in another way in a future release.

## How To:
In [src/js/demo.js](https://github.com/saiij/editable-web-quiz/blob/master/src/js/demo.js) you find the actual demo-questions. Refactor the questions with a category like this:
```
{
    "question": "What or who is 'Dracula vampira'?",
    "answerA": "person",
    "answerB": "plant",
    "answerC": "animal",
    "answerD": "club",
    "correct": "answerB",
    "category": "biology"
},

```

#### Feel free to add your name to the `README.md`-file. If you like the quiz give it a :star:!

**Comment by Trshant** [comment]
hi. i'd like to do this one. which are the categories , though? do let me know. 
even so, i'll add the categories as i think suitable.

**Comment by saiij** [comment]
Hi @Trshant, until now there are now fixed categories. I just think that they need to be general like technologie, sports or biology. If you want to add them you may want to add your categories to the `CONTRIBUTE.md`-file.

**Comment by saiij** [comment]
Assigned to @Trshant

**Comment by Trshant** [comment]
@saiij : did that. Please have a look.

**Comment by saiij** [comment]
@Trshant good work. just changed the category of the first question from fiction to knowledge.
