### ISSUE TITLE
Scribble / Draw or Code a better Menu for this Quiz.

### ISSUE THREAD

**Issue by saiij** [saiij/editable-web-quiz#5]
## Problem:
The User Interface especially the main menu is pretty clunky. To not confuse the user too much. The Menu must become lighter.

#### How To:
If you want to take on this you can scribble/draw/code a new menu. Feel free to add your name on the Readme and also on the footer. After this make a pull request.

**Comment by saiij** [comment]
@skayablars Okay, im looking forward to your pull request!

**Comment by saiij** [comment]
@skayablars Uhm, do you still on it?

**Comment by victoraguilerag** [comment]
I would like to take this ticket

**Comment by saiij** [comment]
## First menu attempt:
![menu animation v1](https://media.giphy.com/media/woDjssq2VtXHyOZtdu/giphy.gif)

**Comment by saiij** [comment]
I will use the text-ui
