### ISSUE TITLE
Add an exit without save option

### ISSUE THREAD

**Issue by saiij** [saiij/editable-web-quiz#6]
# Problem:
At the moment you can only 'save & exit' the game. It would be great to have the possibility to exit the game without saving. 

### How To:
You need to create a new Button with Bootstrap4. To delete saved values you can reuse the delete function. Feel free to add your name to the readme and the footer!

**Comment by Kaivosukeltaja** [comment]
After trying the game I thought I'd suggest just changing "Save & Exit" to just "Exit" and having it save the game just as it does now. From the user's perspective it won't matter that the game gets automatically saved, they can just click "New game" if they don't want to continue the old one. Players might also click the "Exit" button accidentally without realizing they should have clicked on "Save & Exit" instead if they wanted to continue later.

**Comment by saiij** [comment]
@Kaivosukeltaja good point. I will do it this way.

**Comment by lbarros00** [comment]
I have added the requested exit button. However, there are issues with your gameOver function which keeps creating New Game buttons after a game is over.
https://github.com/lbarros00/editable-web-quiz/commit/4e4a595891a25ad62219855f736f9bbc8b263be0
