### ISSUE TITLE
[EASY] Add questions to the quiz. Remains open feel free to contribute!

### ISSUE THREAD

**Issue by saiij** [saiij/editable-web-quiz#7]
# Problem:
This quiz needs more questions. 

## How To Contribute:
In [src/js/demo.js](https://github.com/saiij/editable-web-quiz/blob/master/src/js/demo.js) you find the actual demo-questions. Add more questions with 4 possible answers. Please make sure that these use the following format:
```
{
    "question": "What or who is 'Dracula vampira'?",
    "answerA": "person",
    "answerB": "plant",
    "answerC": "animal",
    "answerD": "club",
    "correct": "answerB",
    "category": "biology"
},
```

Don't get confused, the old questions don't have the category field.  

Feel free to add your name to the [README.md](https://github.com/saiij/editable-web-quiz/blob/master/README.md) file under Contributors. 
If you enjoy this quiz you may want to give it a :star:.

#### Happy Hacktoberfest @all !

**Comment by rht6226** [comment]
Assign this to me

**Comment by praveenscience** [comment]
Added more questions and fixed the issue with `demo.js`.

**Comment by saiij** [comment]
> Assign this to me

Everybody can contribute to this I'm happy with every new question :+1:

**Comment by praveenscience** [comment]
@saiij Start accepting PRs else there will be a lot of merge conflicts... 😞

**Comment by saiij** [comment]
@praveenscience You're right there where a lot of conflicts but I fixed them :smile: !

**Comment by praveenscience** [comment]
@saiij Loads of issues with `demo.js` fixed... 😞

**Comment by abrahamjsb** [comment]
I want contribute adding some more questions...

**Comment by saiij** [comment]
@susantruong Sure no problem, feel free to add more at every time you want!

**Comment by saiij** [comment]
@abrahamjsb No Problem just add them and make a PR ;)

**Comment by praveenscience** [comment]
@saiij Why did you close this? 🤔

**Comment by saiij** [comment]
@praveenscience Whops, this was not intended I reopened it.

**Comment by johnantoni** [comment]
Added some more questions to the quiz, enjoy!

https://github.com/saiij/editable-web-quiz/pull/65

**Comment by saiij** [comment]
@All Thanks for the help!

**Comment by praveenscience** [comment]
It was nice meeting you! 😃

**Comment by saiij** [comment]
@praveenscience Thanks feel free to come back in a few weeks to test the react version!
